package by.dragonsurvivalteam.dragonsurvival.registry.datagen.data_maps;

import by.dragonsurvivalteam.dragonsurvival.common.codecs.DietEntry;
import by.dragonsurvivalteam.dragonsurvival.registry.DSDataMaps;
import by.dragonsurvivalteam.dragonsurvival.registry.DSItems;
import by.dragonsurvivalteam.dragonsurvival.registry.dragon.BuiltInDragonSpecies;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.DataMapProvider;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class DietEntryProvider extends DataMapProvider {
    public DietEntryProvider(final PackOutput output, final CompletableFuture<HolderLookup.Provider> provider) {
        super(output, provider);
    }

    @Override
    protected void gather() {
        builder(DSDataMaps.DIET_ENTRIES)
                .add(BuiltInDragonSpecies.CAVE, caveDiet(), false)
                .add(BuiltInDragonSpecies.FOREST, forestDiet(), false)
                .add(BuiltInDragonSpecies.SEA, seaDiet(), false);
    }

    public static List<DietEntry> caveDiet() {
        return List.of(
                DietEntry.from(ItemTags.COALS, new FoodProperties(1, 1, false, 0.8f, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARGED_COAL.value(), new FoodProperties(6, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARRED_MEAT.value(), new FoodProperties(8, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CAVE_DRAGON_TREAT.value(), new FoodProperties(4, 8, true, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARRED_SEAFOOD.value(), new FoodProperties(7, 11, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARRED_VEGETABLE.value(), new FoodProperties(8, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARRED_MUSHROOM.value(), new FoodProperties(9, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.CHARGED_SOUP.value(), new FoodProperties(15, 15, true, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.HOT_DRAGON_ROD.value(), new FoodProperties(4, 15, true, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.EXPLOSIVE_COPPER.value(), new FoodProperties(6, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.DOUBLE_QUARTZ.value(), new FoodProperties(8, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.QUARTZ_EXPLOSIVE_COPPER.value(), new FoodProperties(12, 18, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:blazefish", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:cooked_magmacubefish_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:blazefish_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:magmacubefish", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:fortress_grouper", new FoodProperties(3, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("desolation:cinder_fruit", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("desolation:powered_cinder_fruit", new FoodProperties(8, 12, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("desolation:activatedcharcoal", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("desolation:infused_powder", new FoodProperties(10, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("desolation:primed_ash", new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("undergarden:ditchbulb", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("xreliquary:molten_core", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("mekanism:dust_coal", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("mekanism:dust_charcoal", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("thermal:coal_coke", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("thermal:basalz_rod", new FoodProperties(2, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("thermal:basalz_powder", new FoodProperties(1, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("create:blaze_cake", new FoodProperties(10, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("create:creative_blaze_cake", new FoodProperties(50, 50, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("nethersdelight:nether_skewer", new FoodProperties(6, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of()))
        );
    }

    public static List<DietEntry> forestDiet() {
        return List.of(
                DietEntry.from(Tags.Items.FOODS_RAW_MEAT, new FoodProperties(6, 4, false, 1.2f, Optional.empty(), List.of())),
                DietEntry.from(Tags.Items.FOODS_BERRY, new FoodProperties(1, 1, false, 1.2f, Optional.empty(), List.of())),
                DietEntry.from(Tags.Items.MUSHROOMS, new FoodProperties(1, 1, false, 0.8f, Optional.empty(), List.of())),
                DietEntry.from(Tags.Items.EGGS, new FoodProperties(2, 2, false, 0.8f, Optional.empty(), List.of())),
                DietEntry.from(Items.SWEET_BERRIES, new FoodProperties(2, 2, false, 0.6f, Optional.empty(), List.of())),
                DietEntry.from(Items.ROTTEN_FLESH, new FoodProperties(2, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.SPIDER_EYE, new FoodProperties(6, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.RABBIT, new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.POISONOUS_POTATO, new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.CHORUS_FRUIT, new FoodProperties(9, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.BROWN_MUSHROOM, new FoodProperties(2, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.RED_MUSHROOM, new FoodProperties(2, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.HONEY_BOTTLE, new FoodProperties(6, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.of(new ItemStack(Items.GLASS_BOTTLE, 1)), List.of())),
                DietEntry.from(Items.WARPED_FUNGUS, new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(Items.CRIMSON_FUNGUS, new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.FOREST_DRAGON_TREAT.value(), new FoodProperties(4, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.MEAT_CHORUS_MIX.value(), new FoodProperties(12, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.MEAT_WILD_BERRIES.value(), new FoodProperties(12, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.SMELLY_MEAT_PORRIDGE.value(), new FoodProperties(6, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.DIAMOND_CHORUS.value(), new FoodProperties(15, 12, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.LUMINOUS_OINTMENT.value(), new FoodProperties(5, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.SWEET_SOUR_RABBIT.value(), new FoodProperties(10, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("additionaldragons:cursed_marrow", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:turtle_soup", new FoodProperties(8, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:wither_bonefish", new FoodProperties(4, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:bonefish", new FoodProperties(4, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("phantasm:chorus_fruit_salad", new FoodProperties(10, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:fiery_chops", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_chimera_chop", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_furlion_chop", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_halycon_beef", new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_charger_shank", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:trilliad_leaves", new FoodProperties(8, 11, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("pamhc2foodextended:rawtofabbititem", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("pamhc2foodextended:rawtofickenitem", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("quark:golden_frog_leg", new FoodProperties(12, 14, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("pamhc2foodextended:rawtofuttonitem", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("alexsmobs:kangaroo_meat", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("alexsmobs:moose_ribs", new FoodProperties(6, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("simplefarming:raw_horse_meat", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("simplefarming:raw_bacon", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("simplefarming:raw_chicken_wings", new FoodProperties(2, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("simplefarming:raw_sausage", new FoodProperties(3, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("xenoclustwo:raw_tortice", new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:musk_ox_shank", new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:frog_legs", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:mangrove_fruit", new FoodProperties(4, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:venisonraw", new FoodProperties(7, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("born_in_chaos_v1:corpse_maggot", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("born_in_chaos_v1:monster_flesh", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:pheasantraw", new FoodProperties(7, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:turkey_leg_raw", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("infernalexp:raw_hogchop", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("infernalexp:cured_jerky", new FoodProperties(10, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("rats:raw_rat", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:frog", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:frog_legs_raw", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:box_turtle", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:arrau_turtle", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:starshell_turtle", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("undergarden:raw_gloomper_leg", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("undergarden:raw_dweller_meat", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("farmersdelight:chicken_cuts", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("farmersdelight:bacon", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("farmersdelight:ham", new FoodProperties(9, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("farmersdelight:minced_beef", new FoodProperties(5, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("farmersdelight:mutton_chops", new FoodProperties(5, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("abnormals_delight:duck_fillet", new FoodProperties(2, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("abnormals_delight:venison_shanks", new FoodProperties(7, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("autumnity:foul_berries", new FoodProperties(2, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("autumnity:turkey", new FoodProperties(7, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("autumnity:turkey_piece", new FoodProperties(2, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("autumnity:foul_soup", new FoodProperties(12, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("endergetic:bolloom_fruit", new FoodProperties(3, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("quark:frog_leg", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("nethers_delight:hoglin_loin", new FoodProperties(8, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("nethers_delight:raw_stuffed_hoglin", new FoodProperties(18, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("xreliquary:zombie_heart", new FoodProperties(4, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("xreliquary:bat_wing", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eidolon:zombie_heart", new FoodProperties(7, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("forbidden_arcanus:bat_wing", new FoodProperties(5, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("twilightforest:raw_venison", new FoodProperties(7, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("twilightforest:raw_meef", new FoodProperties(9, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("twilightforest:hydra_chop", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cyclic:chorus_flight", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cyclic:chorus_spectral", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cyclic:toxic_carrot", new FoodProperties(15, 15, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("artifacts:everlasting_beef", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("byg:soul_shroom", new FoodProperties(9, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("byg:death_cap", new FoodProperties(9, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("minecolonies:chorus_bread", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("wyrmroost:raw_lowtier_meat", new FoodProperties(3, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("wyrmroost:raw_common_meat", new FoodProperties(5, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("wyrmroost:raw_apex_meat", new FoodProperties(8, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("wyrmroost:raw_behemoth_meat", new FoodProperties(11, 12, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("wyrmroost:desert_wyrm", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawchicken_darkbig", new FoodProperties(9, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawchicken_dark", new FoodProperties(5, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawchicken_darksmall", new FoodProperties(3, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawchicken_pale", new FoodProperties(5, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawchicken_palesmall", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("eanimod:rawrabbit_small", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("environmental:duck", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("environmental:venison", new FoodProperties(7, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cnb:lizard_item_jungle", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cnb:lizard_item_mushroom", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cnb:lizard_item_jungle_2", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("cnb:lizard_item_desert_2", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of()))
        );
    }

    public static List<DietEntry> seaDiet() {
        return List.of(
                DietEntry.from(Tags.Items.FOODS_RAW_FISH, new FoodProperties(4, 1, false, 1.2f, Optional.empty(), List.of())),
                DietEntry.from(Items.KELP, new FoodProperties(1, 1, false, 1.0f, Optional.empty(), List.of())),
                DietEntry.from(Tags.Items.EGGS, new FoodProperties(2, 2, false, 0.8f, Optional.empty(), List.of())),
                DietEntry.from(Items.PUFFERFISH, new FoodProperties(8, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.SEA_DRAGON_TREAT.value(), new FoodProperties(4, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.SEASONED_FISH.value(), new FoodProperties(12, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.GOLDEN_CORAL_PUFFERFISH.value(), new FoodProperties(12, 14, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.FROZEN_RAW_FISH.value(), new FoodProperties(2, 1, true, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from(DSItems.GOLDEN_TURTLE_EGG.value(), new FoodProperties(15, 12, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("additionaldragons:slippery_sushi", new FoodProperties(10, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_candlefish", new FoodProperties(9, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_crimson_skipper", new FoodProperties(8, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_fingerfish", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_pearl_stripefish", new FoodProperties(5, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_limefish", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_sailback", new FoodProperties(6, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:soulsucker", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:obsidianfish", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:lava_pufferfish", new FoodProperties(8, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:searing_cod", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:glowdine", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:warped_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:lava_pufferfish_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:glowdine_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:soulsucker_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:obsidianfish_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:searing_cod_slice", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("crittersandcompanions:clam", new FoodProperties(10, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_golden_gullfish", new FoodProperties(10, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_turquoise_stripefish", new FoodProperties(7, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_violet_skipper", new FoodProperties(7, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_rocketfish", new FoodProperties(4, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_crimson_stripefish", new FoodProperties(8, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_sapphire_strider", new FoodProperties(9, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_dark_hatchetfish", new FoodProperties(9, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_ironback", new FoodProperties(10, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_rainbowfish", new FoodProperties(11, 11, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aoa3:raw_razorfish", new FoodProperties(12, 14, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("alexsmobs:lobster_tail", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("alexsmobs:blobfish", new FoodProperties(8, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:raw_ghost_shark", new FoodProperties(8, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:raw_isopod", new FoodProperties(4, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:raw_mudskipper", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:raw_coelacanth", new FoodProperties(9, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:raw_anglerfish", new FoodProperties(6, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:deep_sea_fish", new FoodProperties(4, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oddwatermobs:crab_leg", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("simplefarming:raw_calamari", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:elephantnose_fish", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:flashlight_fish", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("born_in_chaos_v1:sea_terror_eye", new FoodProperties(10, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("born_in_chaos_v1:rotten_fish", new FoodProperties(4, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:rocket_killifish", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:leafy_seadragon", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unnamedanimalmod:elephantnose_fish", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:eel_meat_raw", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:calamari_raw", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betteranimalsplus:crab_meat_raw", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:fish_fillet_raw", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:goldfish", new FoodProperties(8, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:algae", new FoodProperties(3, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betterendforge:end_fish_raw", new FoodProperties(6, 7, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betterendforge:hydralux_petal", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("betterendforge:charnia_green", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("shroomed:raw_shroomfin", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("undergarden:raw_gwibling", new FoodProperties(5, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("bettas:betta_fish", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("quark:crab_leg", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("pamhc2foodextended:rawtofishitem", new FoodProperties(0, 0, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:banded_redback_shrimp", new FoodProperties(6, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:night_light_squid", new FoodProperties(6, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:night_light_squid_tentacle", new FoodProperties(6, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:emerald_spindly_gem_crab", new FoodProperties(7, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:amber_spindly_gem_crab", new FoodProperties(7, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:rubby_spindly_gem_crab", new FoodProperties(7, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:sapphire_spindly_gem_crab", new FoodProperties(7, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:pearl_spindly_gem_crab", new FoodProperties(7, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:papa_wee", new FoodProperties(6, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:bugmeat", new FoodProperties(4, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:raw_golden_river_ray_wing", new FoodProperties(6, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:red_bull_crab_claw", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:white_bull_crab_claw", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("fins:wherble_fin", new FoodProperties(1, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("forbidden_arcanus:tentacle", new FoodProperties(5, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("pneumaticcraft:raw_salmon_tempura", new FoodProperties(6, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("rats:ratfish", new FoodProperties(4, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:purple_pickerelweed", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:blue_pickerelweed", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:polar_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:tongue_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:thorny_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:ochre_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:lionfish", new FoodProperties(8, 9, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquaculture:sushi", new FoodProperties(6, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:fresh_soup", new FoodProperties(15, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:beluga_caviar", new FoodProperties(10, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:piranha", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:tilapia", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:stuffed_piranha", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:tigerfish", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("freshwarriors:toe_biter_leg", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("mysticalworld:raw_squid", new FoodProperties(6, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:fresh_soup", new FoodProperties(10, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:beluga_caviar", new FoodProperties(10, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_piranha", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_tilapia", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:stuffed_piranha", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:tigerfish", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:toe_biter_leg", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_angelfish", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_football_fish", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_foxface_fish", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_royal_gramma", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_starfish", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:spider_crab_leg", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquafina:raw_stingray_slice", new FoodProperties(4, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_ceratodus", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_cyclurus", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_potamoceratodus", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_myledaphus", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_gar", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoricfauna:raw_oyster", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("prehistoric_delight:prehistoric_fillet", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("seadwellers:rainbow_trout", new FoodProperties(10, 10, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("crittersandcompanions:koi_fish", new FoodProperties(5, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquamirae:elodea", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:clam", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:calamari", new FoodProperties(2, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:anchovy", new FoodProperties(3, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:crab", new FoodProperties(6, 8, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:glowing_calamari", new FoodProperties(4, 5, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:oyster", new FoodProperties(2, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:roe", new FoodProperties(1, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:shrimp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("croptopia:tuna", new FoodProperties(6, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("aquamirae:spinefish", new FoodProperties(4, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("alexsmobs:flying_fish", new FoodProperties(6, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:eyeball", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:eyeball_fish", new FoodProperties(3, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:guardian", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:guardian_tail", new FoodProperties(1, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:cut_tentacles", new FoodProperties(3, 1, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:tentacles", new FoodProperties(3, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:tentacle_on_a_stick", new FoodProperties(3, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:fugu_slice", new FoodProperties(5, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:elder_guardian_slice", new FoodProperties(8, 6, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("oceansdelight:elder_guardian_slab", new FoodProperties(15, 15, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("upgrade_aquatic:elder_eye", new FoodProperties(15, 15, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:golden_scau", new FoodProperties(15, 15, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:raw_scau", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:raw_stetha", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:stetha_eggs", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:beelze_eggs", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:scau_eggs", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:ammon_eggs", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("unusualprehistory:dunk_eggs", new FoodProperties(4, 3, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:crimson_seagrass", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:crimson_kelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("netherdepthsupgrade:warped_seagrass", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("undergarden:glitterkelp", new FoodProperties(2, 2, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of())),
                DietEntry.from("enlightened_end:raw_stalker", new FoodProperties(10, 4, false, DietEntry.DEFAULT_EAT_SECONDS, Optional.empty(), List.of()))
        );
    }

    @Override
    public @NotNull String getName() {
        return "Dragon Survival Diet Entries";
    }
}
