package by.dragonsurvivalteam.dragonsurvival.registry.datagen.data_maps;

import by.dragonsurvivalteam.dragonsurvival.common.codecs.DietEntry;
import by.dragonsurvivalteam.dragonsurvival.registry.DSConditions;
import by.dragonsurvivalteam.dragonsurvival.registry.DSDataMaps;
import by.dragonsurvivalteam.dragonsurvival.registry.DSItems;
import by.dragonsurvivalteam.dragonsurvival.registry.dragon.BuiltInDragonSpecies;
import by.dragonsurvivalteam.dragonsurvival.util.Functions;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.DataMapProvider;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.concurrent.CompletableFuture;

public class DietEntryProvider extends DataMapProvider {
    public DietEntryProvider(final PackOutput output, final CompletableFuture<HolderLookup.Provider> provider) {
        super(output, provider);
    }

    @Override
    protected void gather(HolderLookup.@NotNull Provider provider) {
        builder(DSDataMaps.DIET_ENTRIES)
                .add(BuiltInDragonSpecies.CAVE_DRAGON, caveDiet(), false, DSConditions.CAVE_DRAGON_LOADED)
                .add(BuiltInDragonSpecies.FOREST_DRAGON, forestDiet(), false, DSConditions.FOREST_DRAGON_LOADED)
                .add(BuiltInDragonSpecies.SEA_DRAGON, seaDiet(), false, DSConditions.SEA_DRAGON_LOADED);
    }

    public static List<DietEntry> caveDiet() {
        return List.of(
                DietEntry.create(ItemTags.COALS).nutrition(1).saturation(1).fast().build(),
                DietEntry.create(DSItems.CHARGED_COAL.value()).nutrition(6).saturation(1).build(),
                DietEntry.create(DSItems.CHARRED_MEAT.value()).nutrition(8).saturation(10).build(),
                DietEntry.create(DSItems.CAVE_DRAGON_TREAT.value()).nutrition(4).saturation(8).canAlwaysEat().build(),
                DietEntry.create(DSItems.CHARRED_SEAFOOD.value()).nutrition(7).saturation(11).build(),
                DietEntry.create(DSItems.CHARRED_VEGETABLE.value()).nutrition(8).saturation(9).build(),
                DietEntry.create(DSItems.CHARRED_MUSHROOM.value()).nutrition(9).saturation(9).build(),
                DietEntry.create(DSItems.CHARGED_SOUP.value()).nutrition(15).saturation(15).canAlwaysEat().build(),
                DietEntry.create(DSItems.HOT_DRAGON_ROD.value()).nutrition(4).saturation(15).canAlwaysEat().build(),
                DietEntry.create(DSItems.EXPLOSIVE_COPPER.value()).nutrition(6).saturation(4).build(),
                DietEntry.create(DSItems.DOUBLE_QUARTZ.value()).nutrition(8).saturation(6).build(),
                DietEntry.create(DSItems.QUARTZ_EXPLOSIVE_COPPER.value()).nutrition(12).saturation(18).build(),
                DietEntry.create("netherdepthsupgrade:blazefish").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:cooked_magmacubefish_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:blazefish_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:magmacubefish").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:fortress_grouper").nutrition(3).saturation(1).build(),
                DietEntry.create("desolation:cinder_fruit").nutrition(6).saturation(7).build(),
                DietEntry.create("desolation:powered_cinder_fruit").nutrition(8).saturation(12).build(),
                DietEntry.create("desolation:activatedcharcoal").nutrition(2).saturation(2).build(),
                DietEntry.create("desolation:infused_powder").nutrition(10).saturation(10).build(),
                DietEntry.create("desolation:primed_ash").nutrition(7).saturation(8).build(),
                DietEntry.create("undergarden:ditchbulb").nutrition(5).saturation(6).build(),
                DietEntry.create("xreliquary:molten_core").nutrition(1).saturation(1).build(),
                DietEntry.create("mekanism:dust_coal").nutrition(1).saturation(1).build(),
                DietEntry.create("mekanism:dust_charcoal").nutrition(1).saturation(1).build(),
                DietEntry.create("thermal:coal_coke").nutrition(1).saturation(1).build(),
                DietEntry.create("thermal:basalz_rod").nutrition(2).saturation(4).build(),
                DietEntry.create("thermal:basalz_powder").nutrition(1).saturation(2).build(),
                DietEntry.create("create:blaze_cake").nutrition(10).saturation(10).build(),
                DietEntry.create("create:creative_blaze_cake").nutrition(50).saturation(50).build(),
                DietEntry.create("nethersdelight:nether_skewer").nutrition(6).saturation(8).build()
        );
    }

    public static List<DietEntry> forestDiet() {
        return List.of(
                DietEntry.create(Tags.Items.FOODS_RAW_MEAT).nutrition(6).saturation(4).seconds(1.2f).build(),
                DietEntry.create(Tags.Items.FOODS_BERRY).nutrition(1).saturation(1).seconds(1.2f).build(),
                DietEntry.create(Tags.Items.MUSHROOMS).nutrition(1).saturation(1).fast().build(),
                DietEntry.create(Items.SWEET_BERRIES).nutrition(2).saturation(2).seconds(0.6f).build(),
                DietEntry.create(Items.ROTTEN_FLESH).nutrition(2).saturation(4).build(),
                DietEntry.create(Items.SPIDER_EYE).nutrition(6).saturation(8).build(),
                DietEntry.create(Items.RABBIT).nutrition(7).saturation(8).build(),
                DietEntry.create(Items.POISONOUS_POTATO).nutrition(2).saturation(4).build(),
                DietEntry.create(Items.CHORUS_FRUIT).nutrition(9).saturation(8).build(),
                DietEntry.create(Items.BROWN_MUSHROOM).nutrition(2).saturation(1).build(),
                DietEntry.create(Items.RED_MUSHROOM).nutrition(2).saturation(3).build(),
                DietEntry.create(Items.HONEY_BOTTLE).nutrition(6).saturation(1).convertsTo(Items.GLASS_BOTTLE).build(),
                DietEntry.create(Items.WARPED_FUNGUS).nutrition(3).saturation(3).build(),
                DietEntry.create(Items.CRIMSON_FUNGUS).nutrition(3).saturation(3).build(),
                DietEntry.create(DSItems.FOREST_DRAGON_TREAT.value()).nutrition(4).saturation(8).build(),
                DietEntry.create(DSItems.MEAT_CHORUS_MIX.value()).nutrition(12).saturation(8).build(),
                DietEntry.create(DSItems.MEAT_WILD_BERRIES.value()).nutrition(12).saturation(10).build(),
                DietEntry.create(DSItems.SMELLY_MEAT_PORRIDGE.value()).nutrition(6).saturation(10).build(),
                DietEntry.create(DSItems.DIAMOND_CHORUS.value()).nutrition(15).saturation(12).build(),
                DietEntry.create(DSItems.LUMINOUS_OINTMENT.value()).nutrition(5).saturation(3).build(),
                DietEntry.create(DSItems.SWEET_SOUR_RABBIT.value()).nutrition(10).saturation(6).build(),
                DietEntry.create("additionaldragons:cursed_marrow").nutrition(4).saturation(2).fast().build(),
                DietEntry.create("aquaculture:turtle_soup").nutrition(8).saturation(8).build(),
                DietEntry.create("netherdepthsupgrade:wither_bonefish").nutrition(4).saturation(6).build(),
                DietEntry.create("netherdepthsupgrade:bonefish").nutrition(4).saturation(6).build(),
                DietEntry.create("phantasm:chorus_fruit_salad").nutrition(10).saturation(10).build(),
                DietEntry.create("aoa3:fiery_chops").nutrition(6).saturation(7).build(),
                DietEntry.create("aoa3:raw_chimera_chop").nutrition(6).saturation(7).build(),
                DietEntry.create("aoa3:raw_furlion_chop").nutrition(6).saturation(7).build(),
                DietEntry.create("aoa3:raw_halycon_beef").nutrition(7).saturation(8).build(),
                DietEntry.create("aoa3:raw_charger_shank").nutrition(6).saturation(7).build(),
                DietEntry.create("aoa3:trilliad_leaves").nutrition(8).saturation(11).build(),
                DietEntry.create("pamhc2foodextended:rawtofabbititem").nutrition(0).saturation(0).build(),
                DietEntry.create("pamhc2foodextended:rawtofickenitem").nutrition(0).saturation(0).build(),
                DietEntry.create("quark:golden_frog_leg").nutrition(12).saturation(14).build(),
                DietEntry.create("pamhc2foodextended:rawtofuttonitem").nutrition(0).saturation(0).build(),
                DietEntry.create("alexsmobs:kangaroo_meat").nutrition(5).saturation(6).build(),
                DietEntry.create("alexsmobs:moose_ribs").nutrition(6).saturation(8).build(),
                DietEntry.create("simplefarming:raw_horse_meat").nutrition(5).saturation(6).build(),
                DietEntry.create("simplefarming:raw_bacon").nutrition(3).saturation(3).build(),
                DietEntry.create("simplefarming:raw_chicken_wings").nutrition(2).saturation(3).build(),
                DietEntry.create("simplefarming:raw_sausage").nutrition(3).saturation(4).build(),
                DietEntry.create("xenoclustwo:raw_tortice").nutrition(7).saturation(8).build(),
                DietEntry.create("unnamedanimalmod:musk_ox_shank").nutrition(7).saturation(8).build(),
                DietEntry.create("unnamedanimalmod:frog_legs").nutrition(5).saturation(6).build(),
                DietEntry.create("unnamedanimalmod:mangrove_fruit").nutrition(4).saturation(7).build(),
                DietEntry.create("betteranimalsplus:venisonraw").nutrition(7).saturation(6).build(),
                DietEntry.create("born_in_chaos_v1:corpse_maggot").nutrition(1).saturation(1).build(),
                DietEntry.create("born_in_chaos_v1:monster_flesh").nutrition(1).saturation(1).build(),
                DietEntry.create("betteranimalsplus:pheasantraw").nutrition(7).saturation(5).build(),
                DietEntry.create("betteranimalsplus:turkey_leg_raw").nutrition(4).saturation(5).build(),
                DietEntry.create("infernalexp:raw_hogchop").nutrition(6).saturation(7).build(),
                DietEntry.create("infernalexp:cured_jerky").nutrition(10).saturation(7).build(),
                DietEntry.create("rats:raw_rat").nutrition(4).saturation(5).build(),
                DietEntry.create("aquaculture:frog").nutrition(4).saturation(5).build(),
                DietEntry.create("aquaculture:frog_legs_raw").nutrition(4).saturation(4).build(),
                DietEntry.create("aquaculture:box_turtle").nutrition(4).saturation(5).build(),
                DietEntry.create("aquaculture:arrau_turtle").nutrition(4).saturation(5).build(),
                DietEntry.create("aquaculture:starshell_turtle").nutrition(4).saturation(5).build(),
                DietEntry.create("undergarden:raw_gloomper_leg").nutrition(4).saturation(5).build(),
                DietEntry.create("undergarden:raw_dweller_meat").nutrition(6).saturation(7).build(),
                DietEntry.create("farmersdelight:chicken_cuts").nutrition(3).saturation(3).build(),
                DietEntry.create("farmersdelight:bacon").nutrition(3).saturation(3).build(),
                DietEntry.create("farmersdelight:ham").nutrition(9).saturation(10).build(),
                DietEntry.create("farmersdelight:minced_beef").nutrition(5).saturation(3).build(),
                DietEntry.create("farmersdelight:mutton_chops").nutrition(5).saturation(3).build(),
                DietEntry.create("abnormals_delight:duck_fillet").nutrition(2).saturation(3).build(),
                DietEntry.create("abnormals_delight:venison_shanks").nutrition(7).saturation(3).build(),
                DietEntry.create("autumnity:foul_berries").nutrition(2).saturation(4).build(),
                DietEntry.create("autumnity:turkey").nutrition(7).saturation(8).build(),
                DietEntry.create("autumnity:turkey_piece").nutrition(2).saturation(4).build(),
                DietEntry.create("autumnity:foul_soup").nutrition(12).saturation(8).build(),
                DietEntry.create("endergetic:bolloom_fruit").nutrition(3).saturation(4).build(),
                DietEntry.create("quark:frog_leg").nutrition(4).saturation(5).build(),
                DietEntry.create("nethers_delight:hoglin_loin").nutrition(8).saturation(6).build(),
                DietEntry.create("nethers_delight:raw_stuffed_hoglin").nutrition(18).saturation(10).build(),
                DietEntry.create("xreliquary:zombie_heart").nutrition(4).saturation(7).build(),
                DietEntry.create("xreliquary:bat_wing").nutrition(2).saturation(2).build(),
                DietEntry.create("eidolon:zombie_heart").nutrition(7).saturation(7).build(),
                DietEntry.create("forbidden_arcanus:bat_wing").nutrition(5).saturation(2).build(),
                DietEntry.create("twilightforest:raw_venison").nutrition(7).saturation(7).build(),
                DietEntry.create("twilightforest:raw_meef").nutrition(9).saturation(5).build(),
                DietEntry.create("twilightforest:hydra_chop").nutrition(0).saturation(0).build(),
                DietEntry.create("cyclic:chorus_flight").nutrition(0).saturation(0).build(),
                DietEntry.create("cyclic:chorus_spectral").nutrition(0).saturation(0).build(),
                DietEntry.create("cyclic:toxic_carrot").nutrition(15).saturation(15).build(),
                DietEntry.create("artifacts:everlasting_beef").nutrition(0).saturation(0).build(),
                DietEntry.create("byg:soul_shroom").nutrition(9).saturation(5).build(),
                DietEntry.create("byg:death_cap").nutrition(9).saturation(8).build(),
                DietEntry.create("minecolonies:chorus_bread").nutrition(0).saturation(0).build(),
                DietEntry.create("wyrmroost:raw_lowtier_meat").nutrition(3).saturation(2).build(),
                DietEntry.create("wyrmroost:raw_common_meat").nutrition(5).saturation(3).build(),
                DietEntry.create("wyrmroost:raw_apex_meat").nutrition(8).saturation(6).build(),
                DietEntry.create("wyrmroost:raw_behemoth_meat").nutrition(11).saturation(12).build(),
                DietEntry.create("wyrmroost:desert_wyrm").nutrition(4).saturation(3).build(),
                DietEntry.create("eanimod:rawchicken_darkbig").nutrition(9).saturation(5).build(),
                DietEntry.create("eanimod:rawchicken_dark").nutrition(5).saturation(4).build(),
                DietEntry.create("eanimod:rawchicken_darksmall").nutrition(3).saturation(2).build(),
                DietEntry.create("eanimod:rawchicken_pale").nutrition(5).saturation(3).build(),
                DietEntry.create("eanimod:rawchicken_palesmall").nutrition(4).saturation(3).build(),
                DietEntry.create("eanimod:rawrabbit_small").nutrition(4).saturation(4).build(),
                DietEntry.create("environmental:duck").nutrition(4).saturation(3).build(),
                DietEntry.create("environmental:venison").nutrition(7).saturation(7).build(),
                DietEntry.create("cnb:lizard_item_jungle").nutrition(4).saturation(4).build(),
                DietEntry.create("cnb:lizard_item_mushroom").nutrition(4).saturation(4).build(),
                DietEntry.create("cnb:lizard_item_jungle_2").nutrition(4).saturation(4).build(),
                DietEntry.create("cnb:lizard_item_desert_2").nutrition(4).saturation(4).build()
        );
    }

    public static List<DietEntry> seaDiet() {
        return List.of(
                DietEntry.create(Tags.Items.FOODS_RAW_FISH).nutrition(1).saturation(1).seconds(1.2f).build(),
                DietEntry.create(Items.KELP).nutrition(1).saturation(1).seconds(1).build(),
                DietEntry.create(Items.PUFFERFISH).nutrition(8).saturation(8).build(),
                DietEntry.create(DSItems.SEA_DRAGON_TREAT.value()).nutrition(4).saturation(8).build(),
                DietEntry.create(DSItems.SEASONED_FISH.value()).nutrition(12).saturation(10).build(),
                DietEntry.create(DSItems.GOLDEN_CORAL_PUFFERFISH.value()).nutrition(12).saturation(14).build(),
                DietEntry.create(DSItems.FROZEN_RAW_FISH.value()).nutrition(2).saturation(1).canAlwaysEat().build(),
                DietEntry.create(DSItems.GOLDEN_TURTLE_EGG.value()).nutrition(15).saturation(12).build(),
                DietEntry.create("additionaldragons:slippery_sushi").nutrition(10).saturation(8).effect(() -> new MobEffectInstance(MobEffects.DOLPHINS_GRACE, Functions.secondsToTicks(20)), 1).build(),
                DietEntry.create("aoa3:raw_candlefish").nutrition(9).saturation(9).build(),
                DietEntry.create("aoa3:raw_crimson_skipper").nutrition(8).saturation(8).build(),
                DietEntry.create("aoa3:raw_fingerfish").nutrition(4).saturation(4).build(),
                DietEntry.create("aoa3:raw_pearl_stripefish").nutrition(5).saturation(4).build(),
                DietEntry.create("aoa3:raw_limefish").nutrition(5).saturation(5).build(),
                DietEntry.create("aoa3:raw_sailback").nutrition(6).saturation(5).build(),
                DietEntry.create("netherdepthsupgrade:soulsucker").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:obsidianfish").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:lava_pufferfish").nutrition(8).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:searing_cod").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:glowdine").nutrition(6).saturation(7).build(),
                DietEntry.create("netherdepthsupgrade:warped_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:lava_pufferfish_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:glowdine_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:soulsucker_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:obsidianfish_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:searing_cod_slice").nutrition(2).saturation(2).build(),
                DietEntry.create("crittersandcompanions:clam").nutrition(10).saturation(3).build(),
                DietEntry.create("aoa3:raw_golden_gullfish").nutrition(10).saturation(2).build(),
                DietEntry.create("aoa3:raw_turquoise_stripefish").nutrition(7).saturation(6).build(),
                DietEntry.create("aoa3:raw_violet_skipper").nutrition(7).saturation(7).build(),
                DietEntry.create("aoa3:raw_rocketfish").nutrition(4).saturation(10).build(),
                DietEntry.create("aoa3:raw_crimson_stripefish").nutrition(8).saturation(7).build(),
                DietEntry.create("aoa3:raw_sapphire_strider").nutrition(9).saturation(8).build(),
                DietEntry.create("aoa3:raw_dark_hatchetfish").nutrition(9).saturation(9).build(),
                DietEntry.create("aoa3:raw_ironback").nutrition(10).saturation(9).build(),
                DietEntry.create("aoa3:raw_rainbowfish").nutrition(11).saturation(11).build(),
                DietEntry.create("aoa3:raw_razorfish").nutrition(12).saturation(14).build(),
                DietEntry.create("alexsmobs:lobster_tail").nutrition(4).saturation(5).build(),
                DietEntry.create("alexsmobs:blobfish").nutrition(8).saturation(9).build(),
                DietEntry.create("oddwatermobs:raw_ghost_shark").nutrition(8).saturation(8).build(),
                DietEntry.create("oddwatermobs:raw_isopod").nutrition(4).saturation(2).build(),
                DietEntry.create("oddwatermobs:raw_mudskipper").nutrition(6).saturation(7).build(),
                DietEntry.create("oddwatermobs:raw_coelacanth").nutrition(9).saturation(10).build(),
                DietEntry.create("oddwatermobs:raw_anglerfish").nutrition(6).saturation(6).build(),
                DietEntry.create("oddwatermobs:deep_sea_fish").nutrition(4).saturation(2).build(),
                DietEntry.create("oddwatermobs:crab_leg").nutrition(5).saturation(6).build(),
                DietEntry.create("simplefarming:raw_calamari").nutrition(5).saturation(6).build(),
                DietEntry.create("unnamedanimalmod:elephantnose_fish").nutrition(5).saturation(6).build(),
                DietEntry.create("unnamedanimalmod:flashlight_fish").nutrition(5).saturation(6).build(),
                DietEntry.create("born_in_chaos_v1:sea_terror_eye").nutrition(10).saturation(4).build(),
                DietEntry.create("born_in_chaos_v1:rotten_fish").nutrition(4).saturation(2).build(),
                DietEntry.create("unnamedanimalmod:rocket_killifish").nutrition(5).saturation(6).build(),
                DietEntry.create("unnamedanimalmod:leafy_seadragon").nutrition(5).saturation(6).build(),
                DietEntry.create("unnamedanimalmod:elephantnose_fish").nutrition(5).saturation(6).build(),
                DietEntry.create("betteranimalsplus:eel_meat_raw").nutrition(5).saturation(6).build(),
                DietEntry.create("betteranimalsplus:calamari_raw").nutrition(4).saturation(5).build(),
                DietEntry.create("betteranimalsplus:crab_meat_raw").nutrition(4).saturation(4).build(),
                DietEntry.create("aquaculture:fish_fillet_raw").nutrition(2).saturation(2).build(),
                DietEntry.create("aquaculture:goldfish").nutrition(8).saturation(4).build(),
                DietEntry.create("aquaculture:algae").nutrition(3).saturation(2).build(),
                DietEntry.create("betterendforge:end_fish_raw").nutrition(6).saturation(7).build(),
                DietEntry.create("betterendforge:hydralux_petal").nutrition(3).saturation(3).build(),
                DietEntry.create("betterendforge:charnia_green").nutrition(2).saturation(2).build(),
                DietEntry.create("shroomed:raw_shroomfin").nutrition(5).saturation(6).build(),
                DietEntry.create("undergarden:raw_gwibling").nutrition(5).saturation(6).build(),
                DietEntry.create("bettas:betta_fish").nutrition(4).saturation(5).build(),
                DietEntry.create("quark:crab_leg").nutrition(4).saturation(4).build(),
                DietEntry.create("pamhc2foodextended:rawtofishitem").nutrition(0).saturation(0).build(),
                DietEntry.create("fins:banded_redback_shrimp").nutrition(6).saturation(1).build(),
                DietEntry.create("fins:night_light_squid").nutrition(6).saturation(2).build(),
                DietEntry.create("fins:night_light_squid_tentacle").nutrition(6).saturation(2).build(),
                DietEntry.create("fins:emerald_spindly_gem_crab").nutrition(7).saturation(2).build(),
                DietEntry.create("fins:amber_spindly_gem_crab").nutrition(7).saturation(2).build(),
                DietEntry.create("fins:rubby_spindly_gem_crab").nutrition(7).saturation(2).build(),
                DietEntry.create("fins:sapphire_spindly_gem_crab").nutrition(7).saturation(2).build(),
                DietEntry.create("fins:pearl_spindly_gem_crab").nutrition(7).saturation(2).build(),
                DietEntry.create("fins:papa_wee").nutrition(6).saturation(2).build(),
                DietEntry.create("fins:bugmeat").nutrition(4).saturation(2).build(),
                DietEntry.create("fins:raw_golden_river_ray_wing").nutrition(6).saturation(2).build(),
                DietEntry.create("fins:red_bull_crab_claw").nutrition(4).saturation(4).build(),
                DietEntry.create("fins:white_bull_crab_claw").nutrition(4).saturation(4).build(),
                DietEntry.create("fins:wherble_fin").nutrition(1).saturation(1).build(),
                DietEntry.create("forbidden_arcanus:tentacle").nutrition(5).saturation(2).build(),
                DietEntry.create("pneumaticcraft:raw_salmon_tempura").nutrition(6).saturation(10).build(),
                DietEntry.create("rats:ratfish").nutrition(4).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:purple_pickerelweed").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:blue_pickerelweed").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:polar_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:tongue_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:thorny_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:ochre_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("upgrade_aquatic:lionfish").nutrition(8).saturation(9).build(),
                DietEntry.create("aquaculture:sushi").nutrition(6).saturation(5).build(),
                DietEntry.create("freshwarriors:fresh_soup").nutrition(15).saturation(10).build(),
                DietEntry.create("freshwarriors:beluga_caviar").nutrition(10).saturation(3).build(),
                DietEntry.create("freshwarriors:piranha").nutrition(4).saturation(1).build(),
                DietEntry.create("freshwarriors:tilapia").nutrition(4).saturation(1).build(),
                DietEntry.create("freshwarriors:stuffed_piranha").nutrition(4).saturation(1).build(),
                DietEntry.create("freshwarriors:tigerfish").nutrition(5).saturation(5).build(),
                DietEntry.create("freshwarriors:toe_biter_leg").nutrition(3).saturation(3).build(),
                DietEntry.create("mysticalworld:raw_squid").nutrition(6).saturation(5).build(),
                DietEntry.create("aquafina:fresh_soup").nutrition(10).saturation(10).build(),
                DietEntry.create("aquafina:beluga_caviar").nutrition(10).saturation(3).build(),
                DietEntry.create("aquafina:raw_piranha").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_tilapia").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:stuffed_piranha").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:tigerfish").nutrition(5).saturation(5).build(),
                DietEntry.create("aquafina:toe_biter_leg").nutrition(3).saturation(3).build(),
                DietEntry.create("aquafina:raw_angelfish").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_football_fish").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_foxface_fish").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_royal_gramma").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_starfish").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:spider_crab_leg").nutrition(4).saturation(1).build(),
                DietEntry.create("aquafina:raw_stingray_slice").nutrition(4).saturation(1).build(),
                DietEntry.create("prehistoricfauna:raw_ceratodus").nutrition(5).saturation(5).build(),
                DietEntry.create("prehistoricfauna:raw_cyclurus").nutrition(4).saturation(4).build(),
                DietEntry.create("prehistoricfauna:raw_potamoceratodus").nutrition(5).saturation(5).build(),
                DietEntry.create("prehistoricfauna:raw_myledaphus").nutrition(4).saturation(4).build(),
                DietEntry.create("prehistoricfauna:raw_gar").nutrition(4).saturation(4).build(),
                DietEntry.create("prehistoricfauna:raw_oyster").nutrition(4).saturation(3).build(),
                DietEntry.create("prehistoric_delight:prehistoric_fillet").nutrition(3).saturation(3).build(),
                DietEntry.create("seadwellers:rainbow_trout").nutrition(10).saturation(10).build(),
                DietEntry.create("crittersandcompanions:koi_fish").nutrition(5).saturation(5).build(),
                DietEntry.create("aquamirae:elodea").nutrition(3).saturation(3).build(),
                DietEntry.create("croptopia:clam").nutrition(3).saturation(3).build(),
                DietEntry.create("croptopia:calamari").nutrition(2).saturation(3).build(),
                DietEntry.create("croptopia:anchovy").nutrition(3).saturation(2).build(),
                DietEntry.create("croptopia:crab").nutrition(6).saturation(8).build(),
                DietEntry.create("croptopia:glowing_calamari").nutrition(4).saturation(5).build(),
                DietEntry.create("croptopia:oyster").nutrition(2).saturation(4).build(),
                DietEntry.create("croptopia:roe").nutrition(1).saturation(2).build(),
                DietEntry.create("croptopia:shrimp").nutrition(2).saturation(2).build(),
                DietEntry.create("croptopia:tuna").nutrition(6).saturation(4).build(),
                DietEntry.create("aquamirae:spinefish").nutrition(4).saturation(4).build(),
                DietEntry.create("alexsmobs:flying_fish").nutrition(6).saturation(4).build(),
                DietEntry.create("netherdepthsupgrade:eyeball").nutrition(3).saturation(3).build(),
                DietEntry.create("netherdepthsupgrade:eyeball_fish").nutrition(3).saturation(3).build(),
                DietEntry.create("oceansdelight:guardian").nutrition(4).saturation(3).build(),
                DietEntry.create("oceansdelight:guardian_tail").nutrition(1).saturation(3).build(),
                DietEntry.create("oceansdelight:cut_tentacles").nutrition(3).saturation(1).build(),
                DietEntry.create("oceansdelight:tentacles").nutrition(3).saturation(4).build(),
                DietEntry.create("oceansdelight:tentacle_on_a_stick").nutrition(3).saturation(4).build(),
                DietEntry.create("oceansdelight:fugu_slice").nutrition(5).saturation(4).build(),
                DietEntry.create("oceansdelight:elder_guardian_slice").nutrition(8).saturation(6).build(),
                DietEntry.create("oceansdelight:elder_guardian_slab").nutrition(15).saturation(15).build(),
                DietEntry.create("upgrade_aquatic:elder_eye").nutrition(15).saturation(15).build(),
                DietEntry.create("unusualprehistory:golden_scau").nutrition(15).saturation(15).build(),
                DietEntry.create("unusualprehistory:raw_scau").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:raw_stetha").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:stetha_eggs").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:beelze_eggs").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:scau_eggs").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:ammon_eggs").nutrition(4).saturation(3).build(),
                DietEntry.create("unusualprehistory:dunk_eggs").nutrition(4).saturation(3).build(),
                DietEntry.create("netherdepthsupgrade:crimson_seagrass").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:crimson_kelp").nutrition(2).saturation(2).build(),
                DietEntry.create("netherdepthsupgrade:warped_seagrass").nutrition(2).saturation(2).build(),
                DietEntry.create("undergarden:glitterkelp").nutrition(2).saturation(2).build(),
                DietEntry.create("enlightened_end:raw_stalker").nutrition(10).saturation(4).build()
        );
    }

    @Override
    public @NotNull String getName() {
        return "Dragon Survival Diet Entries";
    }
}