modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DragonSurvivalTeam/DragonSurvival/issues"
logoFile = "dragonsurvival.png"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/dragons-survival"
    authors = "${mod_authors}"
    description = '''
        This mod lets you play as a dragon. There are 3 dragon kinds, which have different traits.
        To start, you must create a Dragon Altar where you can choose the dragon type you want to become.
        '''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${neo_version_range}"

[[dependencies.${mod_id}]]
    modId = "geckolib"
    mandatory = true
    versionRange = "${geckolib_version_range}"
    ordering = "NONE"
    side = "CLIENT"