name: Run PR gametests

on:
  pull_request:
  push:
    branches:
      - '1.21.x'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 21
        uses: neoforged/actions/setup-java@main
        with:
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Setup with Gradle
        run: ./gradlew setup

      - name: Run game tests with Gradle
        run: ./gradlew :tests:runGameTestServer

      - name: Run JUnit tests with Gradle
        run: ./gradlew :tests:runUnitTests

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
